#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>
#include <guiddef.h>

extern "C" {

extern const GUID SAMPLEIME_CLSID;

extern const GUID SAMPLEIME_GUID_PROFILE;

extern const GUID SAMPLEIME_GUID_IME_MODE_PRESERVE_KEY;

extern const GUID SAMPLEIME_GUID_DOUBLE_SINGLE_BYTE_PRESERVE_KEY;

extern const GUID SAMPLEIME_GUID_PUNCTUATION_PRESERVE_KEY;

extern const GUID SAMPLEIME_GUID_COMPARTMENT_DOUBLE_SINGLE_BYTE;

extern const GUID SAMPLEIME_GUID_COMPARTMENT_PUNCTUATION;

extern const GUID SAMPLEIME_GUID_DISPLAY_ATTRIBUTE_INPUT;

extern const GUID SAMPLEIME_GUID_DISPLAY_ATTRIBUTE_CONVERTED;

extern const GUID SAMPLEIME_GUID_CAND_UIELEMENT;

} // extern "C"
