[workspace]
members = [
    "composition_processor",
    "dictionary_parser",
    "globals",
    "ime",
    "input_processor",
    "itf_components",
    "numberkey_windows",
    "ruststringrange",
    "window_classes",
]
